#!/usr/bin/env python3
"""Generate explicit OpenACC traversal for every device-policy allocatable leaf."""

from __future__ import annotations

import argparse
import importlib.util
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INVENTORY_SCRIPT = ROOT / "scripts" / "inventory_persistent_arrays.py"
DATATYPES = ROOT / "src" / "datatypes.f90"
OUTPUT = ROOT / "src" / "device_data_openacc.f90"
DEVICE_POLICIES = {"copyin", "create"}


def load_inventory():
    spec = importlib.util.spec_from_file_location("wql_inventory", INVENTORY_SCRIPT)
    if spec is None or spec.loader is None:
        raise RuntimeError("cannot load persistent-array inventory")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.inventory(DATATYPES)


def owner_routine(owner: str, components: list[str], action: str) -> list[str]:
    verb = {"enter": "map", "check": "check", "exit": "unmap"}[action]
    lines = [
        f"  subroutine {action}_{owner}(value, leaf_count, payload_bytes)",
        f"    type({owner}), intent(inout) :: value",
        "    integer, intent(inout) :: leaf_count",
        "    integer(int64), intent(inout) :: payload_bytes",
    ]
    items = components if action == "enter" else list(reversed(components))
    for name in items:
        lines.append(f"    call {verb}_leaf(value%{name}, leaf_count, payload_bytes)")
    lines.extend([f"  end subroutine {action}_{owner}", ""])
    return lines


def generate() -> str:
    rows = load_inventory()
    grouped: dict[str, list[str]] = defaultdict(list)
    for row in rows:
        owner, name, policy = row[0], row[1], row[6]
        if policy in DEVICE_POLICIES:
            grouped[owner].append(name)
    expected = sum(map(len, grouped.values()))
    if expected != 158:
        raise RuntimeError(f"expected 158 device leaves, found {expected}")

    owners = [
        "block_grid_t", "block_material", "block_plastic", "block_fields",
        "block_boundary", "moment_tensor", "block_pml", "block_type", "iface_type",
    ]
    text = f"""! Generated by scripts/generate_device_data_openacc.py; do not edit manually.
module device_data
  use, intrinsic :: iso_fortran_env, only : int64, error_unit
  use mpi
  use openacc
  use datatypes
  implicit none
  private

  logical, save :: data_active = .false.
  integer, save :: active_leaf_count = 0
  integer(int64), save :: active_payload_bytes = 0_int64
  integer(int64), save :: free_bytes_before = -1_int64

  public :: enter_domain_device_data, assert_domain_device_data_present, &
       exit_domain_device_data

  interface map_leaf
     module procedure map_real_1, map_real_2, map_real_3, map_real_4
     module procedure map_integer_1, map_character_1
  end interface map_leaf
  interface unmap_leaf
     module procedure unmap_real_1, unmap_real_2, unmap_real_3, unmap_real_4
     module procedure unmap_integer_1, unmap_character_1
  end interface unmap_leaf

contains

  subroutine enter_domain_device_data(D)
    type(domain_type), intent(inout) :: D
    integer :: i, j, leaf_count, ierr, rank
    integer(int64) :: payload_bytes, free_after, measured_bytes

    if (data_active) call device_data_error('RUN-DEVICE-DATA-001', &
         'Device data is already active.')
    free_bytes_before = acc_get_property(acc_get_device_num(acc_device_nvidia), &
         acc_device_nvidia, acc_property_free_memory)
    leaf_count = 0
    payload_bytes = 0_int64
    do i = 1, D%nblocks
       call enter_block_grid_t(D%B(i)%G, leaf_count, payload_bytes)
       call enter_block_material(D%B(i)%M, leaf_count, payload_bytes)
       call enter_block_plastic(D%B(i)%P, leaf_count, payload_bytes)
       call enter_block_fields(D%B(i)%F, leaf_count, payload_bytes)
       do j = 1, 6
          call enter_block_boundary(D%B(i)%B(j), leaf_count, payload_bytes)
          call enter_block_pml(D%B(i)%PMLB(j), leaf_count, payload_bytes)
       end do
       call enter_moment_tensor(D%B(i)%MT, leaf_count, payload_bytes)
       call enter_block_type(D%B(i), leaf_count, payload_bytes)
    end do
    do i = 1, D%nifaces
       call enter_iface_type(D%I(i), leaf_count, payload_bytes)
    end do
    call assert_traversal_matches_inventory(leaf_count, payload_bytes, D)
    free_after = acc_get_property(acc_get_device_num(acc_device_nvidia), &
         acc_device_nvidia, acc_property_free_memory)
    measured_bytes = max(0_int64, free_bytes_before - free_after)
    data_active = .true.
    active_leaf_count = leaf_count
    active_payload_bytes = payload_bytes
    call MPI_Comm_rank(MPI_COMM_WORLD, rank, ierr)
    if (rank == 0) then
       write(*,'(A)') 'Persistent OpenACC device data:'
       write(*,'(A,I0)') '  mapped allocatable leaves:  ', leaf_count
       write(*,'(A,F12.3,A)') '  explicit payload:           ', &
            real(payload_bytes,8)/1048576.0_8, ' MiB'
       write(*,'(A,F12.3,A)') '  measured free-memory delta: ', &
            real(measured_bytes,8)/1048576.0_8, ' MiB'
       write(*,'(A,F12.3,A)') '  runtime/allocator overhead: ', &
            real(measured_bytes-payload_bytes,8)/1048576.0_8, ' MiB'
       write(*,'(A)') '  presence decision:          PASS'
    end if
  end subroutine enter_domain_device_data

  subroutine assert_domain_device_data_present(D)
    type(domain_type), intent(inout) :: D
    integer :: i, j, leaf_count
    integer(int64) :: payload_bytes
    if (.not.data_active) call device_data_error('RUN-DEVICE-DATA-002', &
         'Device data presence requested outside its lifetime.')
    leaf_count = 0
    payload_bytes = 0_int64
    do i = 1, D%nblocks
       call check_block_grid_t(D%B(i)%G, leaf_count, payload_bytes)
       call check_block_material(D%B(i)%M, leaf_count, payload_bytes)
       call check_block_plastic(D%B(i)%P, leaf_count, payload_bytes)
       call check_block_fields(D%B(i)%F, leaf_count, payload_bytes)
       do j = 1, 6
          call check_block_boundary(D%B(i)%B(j), leaf_count, payload_bytes)
          call check_block_pml(D%B(i)%PMLB(j), leaf_count, payload_bytes)
       end do
       call check_moment_tensor(D%B(i)%MT, leaf_count, payload_bytes)
       call check_block_type(D%B(i), leaf_count, payload_bytes)
    end do
    do i = 1, D%nifaces
       call check_iface_type(D%I(i), leaf_count, payload_bytes)
    end do
    if (leaf_count /= active_leaf_count .or. payload_bytes /= active_payload_bytes) &
         call device_data_error('RUN-DEVICE-DATA-003', &
         'Allocated leaf ownership changed during the persistent lifetime.')
  end subroutine assert_domain_device_data_present

  subroutine exit_domain_device_data(D)
    type(domain_type), intent(inout) :: D
    integer :: i, j, leaf_count, ierr, rank
    integer(int64) :: payload_bytes, free_after
    if (.not.data_active) call device_data_error('RUN-DEVICE-DATA-004', &
         'Device data exit requested without active ownership.')
    call assert_domain_device_data_present(D)
    leaf_count = 0
    payload_bytes = 0_int64
    do i = D%nifaces, 1, -1
       call exit_iface_type(D%I(i), leaf_count, payload_bytes)
    end do
    do i = D%nblocks, 1, -1
       call exit_block_type(D%B(i), leaf_count, payload_bytes)
       call exit_moment_tensor(D%B(i)%MT, leaf_count, payload_bytes)
       do j = 6, 1, -1
          call exit_block_pml(D%B(i)%PMLB(j), leaf_count, payload_bytes)
          call exit_block_boundary(D%B(i)%B(j), leaf_count, payload_bytes)
       end do
       call exit_block_fields(D%B(i)%F, leaf_count, payload_bytes)
       call exit_block_plastic(D%B(i)%P, leaf_count, payload_bytes)
       call exit_block_material(D%B(i)%M, leaf_count, payload_bytes)
       call exit_block_grid_t(D%B(i)%G, leaf_count, payload_bytes)
    end do
    if (leaf_count /= active_leaf_count .or. payload_bytes /= active_payload_bytes) &
         call device_data_error('RUN-DEVICE-DATA-005', &
         'Reverse cleanup did not traverse the active device ownership set.')
    free_after = acc_get_property(acc_get_device_num(acc_device_nvidia), &
         acc_device_nvidia, acc_property_free_memory)
    data_active = .false.
    active_leaf_count = 0
    active_payload_bytes = 0_int64
    call MPI_Comm_rank(MPI_COMM_WORLD, rank, ierr)
    if (rank == 0) then
       write(*,'(A,F12.3,A)') '  cleanup free-memory recovery: ', &
            real(free_after-free_bytes_before,8)/1048576.0_8, ' MiB relative to entry'
       write(*,'(A)') '  cleanup decision:           PASS'
    end if
  end subroutine exit_domain_device_data

  subroutine assert_traversal_matches_inventory(leaf_count, payload_bytes, D)
    use persistent_memory, only : persistent_memory_bytes
    integer, intent(in) :: leaf_count
    integer(int64), intent(in) :: payload_bytes
    type(domain_type), intent(in) :: D
    integer(int64) :: category(7)
    call persistent_memory_bytes(D, category)
    if (payload_bytes /= sum(category(1:6))) call device_data_error( &
         'RUN-DEVICE-DATA-006', 'Explicit device traversal disagrees with the payload inventory.')
    if (leaf_count < 1) call device_data_error('RUN-DEVICE-DATA-007', &
         'No allocated device-policy leaves were found.')
  end subroutine assert_traversal_matches_inventory

  subroutine device_data_error(code, message)
    character(*), intent(in) :: code, message
    integer :: ierr, rank
    call MPI_Comm_rank(MPI_COMM_WORLD, rank, ierr)
    if (rank == 0) then
       write(error_unit,'(/,A,A)') 'FATAL  ', trim(code)
       write(error_unit,'(A,A)') '  ', trim(message)
       flush(error_unit)
    end if
    call MPI_Abort(MPI_COMM_WORLD, 96, ierr)
  end subroutine device_data_error

"""
    lines = text.splitlines()
    for owner in owners:
        lines += owner_routine(owner, grouped[owner], "enter")
        lines += owner_routine(owner, grouped[owner], "check")
        lines += owner_routine(owner, grouped[owner], "exit")

    helpers = """
  subroutine account_leaf(element_count, bits, leaf_count, payload_bytes)
    integer, intent(in) :: element_count, bits
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    leaf_count = leaf_count + 1
    payload_bytes = payload_bytes + int(element_count,int64)*int(bits/8,int64)
  end subroutine account_leaf

  subroutine map_real_1(value, leaf_count, payload_bytes)
    real(kind=wp), allocatable, intent(inout) :: value(:)
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    if (.not.allocated(value)) return
    call acc_copyin(value)
    if (.not.acc_is_present(value)) call device_data_error('RUN-DEVICE-DATA-008','Real rank-1 leaf is absent after copyin.')
    call account_leaf(size(value), storage_size(0.0_wp), leaf_count, payload_bytes)
  end subroutine
  subroutine map_real_2(value, leaf_count, payload_bytes)
    real(kind=wp), allocatable, intent(inout) :: value(:,:)
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    if (.not.allocated(value)) return
    call acc_copyin(value)
    if (.not.acc_is_present(value)) call device_data_error('RUN-DEVICE-DATA-008','Real rank-2 leaf is absent after copyin.')
    call account_leaf(size(value), storage_size(0.0_wp), leaf_count, payload_bytes)
  end subroutine
  subroutine map_real_3(value, leaf_count, payload_bytes)
    real(kind=wp), allocatable, intent(inout) :: value(:,:,:)
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    if (.not.allocated(value)) return
    call acc_copyin(value)
    if (.not.acc_is_present(value)) call device_data_error('RUN-DEVICE-DATA-008','Real rank-3 leaf is absent after copyin.')
    call account_leaf(size(value), storage_size(0.0_wp), leaf_count, payload_bytes)
  end subroutine
  subroutine map_real_4(value, leaf_count, payload_bytes)
    real(kind=wp), allocatable, intent(inout) :: value(:,:,:,:)
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    if (.not.allocated(value)) return
    call acc_copyin(value)
    if (.not.acc_is_present(value)) call device_data_error('RUN-DEVICE-DATA-008','Real rank-4 leaf is absent after copyin.')
    call account_leaf(size(value), storage_size(0.0_wp), leaf_count, payload_bytes)
  end subroutine
  subroutine map_integer_1(value, leaf_count, payload_bytes)
    integer, allocatable, intent(inout) :: value(:)
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    if (.not.allocated(value)) return
    call acc_copyin(value)
    if (.not.acc_is_present(value)) call device_data_error('RUN-DEVICE-DATA-008','Integer leaf is absent after copyin.')
    call account_leaf(size(value), storage_size(0), leaf_count, payload_bytes)
  end subroutine
  subroutine map_character_1(value, leaf_count, payload_bytes)
    character(len=64), allocatable, intent(inout) :: value(:)
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    if (.not.allocated(value)) return
    call acc_copyin(value)
    if (.not.acc_is_present(value)) call device_data_error('RUN-DEVICE-DATA-008','Character leaf is absent after copyin.')
    call account_leaf(size(value), storage_size(value), leaf_count, payload_bytes)
  end subroutine
"""
    lines += helpers.splitlines()
    # check/unmap are mechanically identical by rank apart from the runtime call.
    for prefix, operation in (("check", ""), ("unmap", "call acc_delete(value)")):
        for typename, declaration, zero in (
            ("real_1", "real(kind=wp), allocatable, intent(inout) :: value(:)", "0.0_wp"),
            ("real_2", "real(kind=wp), allocatable, intent(inout) :: value(:,:)", "0.0_wp"),
            ("real_3", "real(kind=wp), allocatable, intent(inout) :: value(:,:,:)", "0.0_wp"),
            ("real_4", "real(kind=wp), allocatable, intent(inout) :: value(:,:,:,:)", "0.0_wp"),
            ("integer_1", "integer, allocatable, intent(inout) :: value(:)", "0"),
            ("character_1", "character(len=64), allocatable, intent(inout) :: value(:)", "value"),
        ):
            lines += [
                f"  subroutine {prefix}_{typename}(value, leaf_count, payload_bytes)",
                f"    {declaration}",
                "    integer, intent(inout) :: leaf_count",
                "    integer(int64), intent(inout) :: payload_bytes",
                "    if (.not.allocated(value)) return",
                "    if (.not.acc_is_present(value)) call device_data_error('RUN-DEVICE-DATA-009','Mapped leaf is unexpectedly absent.')",
            ]
            if operation:
                lines += [operation, "    if (acc_is_present(value)) call device_data_error('RUN-DEVICE-DATA-010','Leaf remains present after delete.')"]
            lines += [f"    call account_leaf(size(value), storage_size({zero}), leaf_count, payload_bytes)", "  end subroutine", ""]
    lines += ["end module device_data", ""]
    # Add missing generic interfaces generated above.
    insertion = [
        "  interface check_leaf",
        "     module procedure check_real_1, check_real_2, check_real_3, check_real_4",
        "     module procedure check_integer_1, check_character_1",
        "  end interface check_leaf",
    ]
    idx = lines.index("  interface unmap_leaf")
    lines[idx:idx] = insertion
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != generated:
            raise SystemExit("device_data_openacc.f90 is stale; regenerate it")
        print("PASS: explicit OpenACC traversal covers 158 device-policy declarations")
        return 0
    OUTPUT.write_text(generated)
    print(f"Wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
