! Generated by scripts/generate_device_data_openacc.py; do not edit manually.
module device_data
  use, intrinsic :: iso_fortran_env, only : int64, error_unit
  use mpi
  use openacc
  use datatypes
  implicit none
  private

  logical, save :: data_active = .false.
  integer, save :: active_leaf_count = 0
  integer(int64), save :: active_payload_bytes = 0_int64
  integer(int64), save :: free_bytes_before = -1_int64

  public :: enter_domain_device_data, assert_domain_device_data_present, &
       update_domain_host_data, exit_domain_device_data

  interface map_leaf
     module procedure map_real_1, map_real_2, map_real_3, map_real_4
     module procedure map_integer_1, map_character_1
  end interface map_leaf
  interface check_leaf
     module procedure check_real_1, check_real_2, check_real_3, check_real_4
     module procedure check_integer_1, check_character_1
  end interface check_leaf
  interface unmap_leaf
     module procedure unmap_real_1, unmap_real_2, unmap_real_3, unmap_real_4
     module procedure unmap_integer_1, unmap_character_1
  end interface unmap_leaf
  interface update_host_leaf
     module procedure update_host_real_1, update_host_real_2, update_host_real_3, update_host_real_4
     module procedure update_host_integer_1, update_host_character_1
  end interface update_host_leaf

contains

  subroutine enter_domain_device_data(D)
    type(domain_type), intent(inout) :: D
    integer :: i, j, leaf_count, ierr, rank
    integer(int64) :: payload_bytes, free_after, measured_bytes

    if (data_active) call device_data_error('RUN-DEVICE-DATA-001', &
         'Device data is already active.')
    free_bytes_before = acc_get_property(acc_get_device_num(acc_device_nvidia), &
         acc_device_nvidia, acc_property_free_memory)
    leaf_count = 0
    payload_bytes = 0_int64
    do i = 1, D%nblocks
       call enter_block_grid_t(D%B(i)%G, leaf_count, payload_bytes)
       call enter_block_material(D%B(i)%M, leaf_count, payload_bytes)
       call enter_block_plastic(D%B(i)%P, leaf_count, payload_bytes)
       call enter_block_fields(D%B(i)%F, leaf_count, payload_bytes)
       do j = 1, 6
          call enter_block_boundary(D%B(i)%B(j), leaf_count, payload_bytes)
          call enter_block_pml(D%B(i)%PMLB(j), leaf_count, payload_bytes)
       end do
       call enter_moment_tensor(D%B(i)%MT, leaf_count, payload_bytes)
       call enter_block_type(D%B(i), leaf_count, payload_bytes)
    end do
    do i = 1, D%nifaces
       call enter_iface_type(D%I(i), leaf_count, payload_bytes)
    end do
    call assert_traversal_matches_inventory(leaf_count, payload_bytes, D)
    free_after = acc_get_property(acc_get_device_num(acc_device_nvidia), &
         acc_device_nvidia, acc_property_free_memory)
    measured_bytes = max(0_int64, free_bytes_before - free_after)
    if (environment_true('WQL3D_PHASE3_MEMORY_RECONCILE')) then
       if (measured_bytes < payload_bytes .or. measured_bytes > payload_bytes + &
           max(67108864_int64, payload_bytes/20_int64)) call device_data_error( &
           'RUN-DEVICE-DATA-011', 'Measured device allocation disagrees with payload plus allowed overhead.')
    end if
    data_active = .true.
    active_leaf_count = leaf_count
    active_payload_bytes = payload_bytes
    call MPI_Comm_rank(MPI_COMM_WORLD, rank, ierr)
    if (rank == 0) then
       write(*,'(A)') 'Persistent OpenACC device data:'
       write(*,'(A,I0)') '  mapped allocatable leaves:  ', leaf_count
       write(*,'(A,F12.3,A)') '  explicit payload:           ', &
            real(payload_bytes,8)/1048576.0_8, ' MiB'
       write(*,'(A,F12.3,A)') '  measured free-memory delta: ', &
            real(measured_bytes,8)/1048576.0_8, ' MiB'
       write(*,'(A,F12.3,A)') '  runtime/allocator overhead: ', &
            real(measured_bytes-payload_bytes,8)/1048576.0_8, ' MiB'
       write(*,'(A)') '  presence decision:          PASS'
    end if
  end subroutine enter_domain_device_data

  subroutine assert_domain_device_data_present(D)
    type(domain_type), intent(inout) :: D
    integer :: i, j, leaf_count
    integer(int64) :: payload_bytes
    if (.not.data_active) call device_data_error('RUN-DEVICE-DATA-002', &
         'Device data presence requested outside its lifetime.')
    leaf_count = 0
    payload_bytes = 0_int64
    do i = 1, D%nblocks
       call check_block_grid_t(D%B(i)%G, leaf_count, payload_bytes)
       call check_block_material(D%B(i)%M, leaf_count, payload_bytes)
       call check_block_plastic(D%B(i)%P, leaf_count, payload_bytes)
       call check_block_fields(D%B(i)%F, leaf_count, payload_bytes)
       do j = 1, 6
          call check_block_boundary(D%B(i)%B(j), leaf_count, payload_bytes)
          call check_block_pml(D%B(i)%PMLB(j), leaf_count, payload_bytes)
       end do
       call check_moment_tensor(D%B(i)%MT, leaf_count, payload_bytes)
       call check_block_type(D%B(i), leaf_count, payload_bytes)
    end do
    do i = 1, D%nifaces
       call check_iface_type(D%I(i), leaf_count, payload_bytes)
    end do
    if (leaf_count /= active_leaf_count .or. payload_bytes /= active_payload_bytes) &
         call device_data_error('RUN-DEVICE-DATA-003', &
         'Allocated leaf ownership changed during the persistent lifetime.')
  end subroutine assert_domain_device_data_present

  subroutine update_domain_host_data(D)
    type(domain_type), intent(inout) :: D
    integer :: i, j, leaf_count
    integer(int64) :: payload_bytes
    if (.not.data_active) call device_data_error('RUN-DEVICE-DATA-012', &
         'Host update requested outside the persistent device-data lifetime.')
    leaf_count = 0
    payload_bytes = 0_int64
    do i = 1, D%nblocks
       call update_host_block_material(D%B(i)%M, leaf_count, payload_bytes)
       call update_host_block_plastic(D%B(i)%P, leaf_count, payload_bytes)
       call update_host_block_fields(D%B(i)%F, leaf_count, payload_bytes)
       do j = 1, 6
          call update_host_block_boundary(D%B(i)%B(j), leaf_count, payload_bytes)
          call update_host_block_pml(D%B(i)%PMLB(j), leaf_count, payload_bytes)
       end do
       call update_host_block_type(D%B(i), leaf_count, payload_bytes)
    end do
    do i = 1, D%nifaces
       call update_host_iface_type(D%I(i), leaf_count, payload_bytes)
    end do
  end subroutine update_domain_host_data

  subroutine exit_domain_device_data(D)
    type(domain_type), intent(inout) :: D
    integer :: i, j, leaf_count, ierr, rank
    integer(int64) :: payload_bytes, free_after
    if (.not.data_active) call device_data_error('RUN-DEVICE-DATA-004', &
         'Device data exit requested without active ownership.')
    call assert_domain_device_data_present(D)
    leaf_count = 0
    payload_bytes = 0_int64
    do i = D%nifaces, 1, -1
       call exit_iface_type(D%I(i), leaf_count, payload_bytes)
    end do
    do i = D%nblocks, 1, -1
       call exit_block_type(D%B(i), leaf_count, payload_bytes)
       call exit_moment_tensor(D%B(i)%MT, leaf_count, payload_bytes)
       do j = 6, 1, -1
          call exit_block_pml(D%B(i)%PMLB(j), leaf_count, payload_bytes)
          call exit_block_boundary(D%B(i)%B(j), leaf_count, payload_bytes)
       end do
       call exit_block_fields(D%B(i)%F, leaf_count, payload_bytes)
       call exit_block_plastic(D%B(i)%P, leaf_count, payload_bytes)
       call exit_block_material(D%B(i)%M, leaf_count, payload_bytes)
       call exit_block_grid_t(D%B(i)%G, leaf_count, payload_bytes)
    end do
    if (leaf_count /= active_leaf_count .or. payload_bytes /= active_payload_bytes) &
         call device_data_error('RUN-DEVICE-DATA-005', &
         'Reverse cleanup did not traverse the active device ownership set.')
    free_after = acc_get_property(acc_get_device_num(acc_device_nvidia), &
         acc_device_nvidia, acc_property_free_memory)
    data_active = .false.
    active_leaf_count = 0
    active_payload_bytes = 0_int64
    call MPI_Comm_rank(MPI_COMM_WORLD, rank, ierr)
    if (rank == 0) then
       write(*,'(A,F12.3,A)') '  cleanup free-memory recovery: ', &
            real(free_after-free_bytes_before,8)/1048576.0_8, ' MiB relative to entry'
       write(*,'(A)') '  cleanup decision:           PASS'
    end if
  end subroutine exit_domain_device_data

  subroutine assert_traversal_matches_inventory(leaf_count, payload_bytes, D)
    use persistent_memory, only : persistent_memory_bytes
    integer, intent(in) :: leaf_count
    integer(int64), intent(in) :: payload_bytes
    type(domain_type), intent(in) :: D
    integer(int64) :: category(7)
    call persistent_memory_bytes(D, category)
    if (payload_bytes /= sum(category(1:6))) call device_data_error( &
         'RUN-DEVICE-DATA-006', 'Explicit device traversal disagrees with the payload inventory.')
    if (leaf_count < 1) call device_data_error('RUN-DEVICE-DATA-007', &
         'No allocated device-policy leaves were found.')
  end subroutine assert_traversal_matches_inventory

  subroutine device_data_error(code, message)
    character(*), intent(in) :: code, message
    integer :: ierr, rank
    call MPI_Comm_rank(MPI_COMM_WORLD, rank, ierr)
    if (rank == 0) then
       write(error_unit,'(/,A,A)') 'FATAL  ', trim(code)
       write(error_unit,'(A,A)') '  ', trim(message)
       flush(error_unit)
    end if
    call MPI_Abort(MPI_COMM_WORLD, 96, ierr)
  end subroutine device_data_error

  logical function environment_true(name)
    character(*), intent(in) :: name
    character(16) :: value
    integer :: status
    value = ''
    call get_environment_variable(name, value, status=status)
    environment_true = status == 0 .and. any(trim(adjustl(value)) == &
         [character(len=5) :: '1', 'true', 'TRUE', 'yes', 'YES'])
  end function environment_true

  subroutine enter_block_grid_t(value, leaf_count, payload_bytes)
    type(block_grid_t), intent(inout) :: value
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    call map_leaf(value%x, leaf_count, payload_bytes)
    call map_leaf(value%metricx, leaf_count, payload_bytes)
    call map_leaf(value%metricy, leaf_count, payload_bytes)
    call map_leaf(value%metricz, leaf_count, payload_bytes)
    call map_leaf(value%J, leaf_count, payload_bytes)
  end subroutine enter_block_grid_t

  subroutine check_block_grid_t(value, leaf_count, payload_bytes)
    type(block_grid_t), intent(inout) :: value
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    call check_leaf(value%J, leaf_count, payload_bytes)
    call check_leaf(value%metricz, leaf_count, payload_bytes)
    call check_leaf(value%metricy, leaf_count, payload_bytes)
    call check_leaf(value%metricx, leaf_count, payload_bytes)
    call check_leaf(value%x, leaf_count, payload_bytes)
  end subroutine check_block_grid_t

  subroutine exit_block_grid_t(value, leaf_count, payload_bytes)
    type(block_grid_t), intent(inout) :: value
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    call unmap_leaf(value%J, leaf_count, payload_bytes)
    call unmap_leaf(value%metricz, leaf_count, payload_bytes)
    call unmap_leaf(value%metricy, leaf_count, payload_bytes)
    call unmap_leaf(value%metricx, leaf_count, payload_bytes)
    call unmap_leaf(value%x, leaf_count, payload_bytes)
  end subroutine exit_block_grid_t

  subroutine enter_block_material(value, leaf_count, payload_bytes)
    type(block_material), intent(inout) :: value
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    call map_leaf(value%M, leaf_count, payload_bytes)
    call map_leaf(value%Qp_inv, leaf_count, payload_bytes)
    call map_leaf(value%Qs_inv, leaf_count, payload_bytes)
    call map_leaf(value%eta4, leaf_count, payload_bytes)
    call map_leaf(value%eta5, leaf_count, payload_bytes)
    call map_leaf(value%eta6, leaf_count, payload_bytes)
    call map_leaf(value%eta7, leaf_count, payload_bytes)
    call map_leaf(value%eta8, leaf_count, payload_bytes)
    call map_leaf(value%eta9, leaf_count, payload_bytes)
    call map_leaf(value%Deta4, leaf_count, payload_bytes)
    call map_leaf(value%Deta5, leaf_count, payload_bytes)
    call map_leaf(value%Deta6, leaf_count, payload_bytes)
    call map_leaf(value%Deta7, leaf_count, payload_bytes)
    call map_leaf(value%Deta8, leaf_count, payload_bytes)
    call map_leaf(value%Deta9, leaf_count, payload_bytes)
    call map_leaf(value%Qp_inv_Q, leaf_count, payload_bytes)
    call map_leaf(value%Qs_inv_Q, leaf_count, payload_bytes)
    call map_leaf(value%eta4Q, leaf_count, payload_bytes)
    call map_leaf(value%eta5Q, leaf_count, payload_bytes)
    call map_leaf(value%eta6Q, leaf_count, payload_bytes)
    call map_leaf(value%eta7Q, leaf_count, payload_bytes)
    call map_leaf(value%eta8Q, leaf_count, payload_bytes)
    call map_leaf(value%eta9Q, leaf_count, payload_bytes)
    call map_leaf(value%Deta4Q, leaf_count, payload_bytes)
    call map_leaf(value%Deta5Q, leaf_count, payload_bytes)
    call map_leaf(value%Deta6Q, leaf_count, payload_bytes)
    call map_leaf(value%Deta7Q, leaf_count, payload_bytes)
    call map_leaf(value%Deta8Q, leaf_count, payload_bytes)
    call map_leaf(value%Deta9Q, leaf_count, payload_bytes)
    call map_leaf(value%Qp_inv_Q8, leaf_count, payload_bytes)
    call map_leaf(value%Qs_inv_Q8, leaf_count, payload_bytes)
    call map_leaf(value%eta4Q8, leaf_count, payload_bytes)
    call map_leaf(value%eta5Q8, leaf_count, payload_bytes)
    call map_leaf(value%eta6Q8, leaf_count, payload_bytes)
    call map_leaf(value%eta7Q8, leaf_count, payload_bytes)
    call map_leaf(value%eta8Q8, leaf_count, payload_bytes)
    call map_leaf(value%eta9Q8, leaf_count, payload_bytes)
    call map_leaf(value%Deta4Q8, leaf_count, payload_bytes)
    call map_leaf(value%Deta5Q8, leaf_count, payload_bytes)
    call map_leaf(value%Deta6Q8, leaf_count, payload_bytes)
    call map_leaf(value%Deta7Q8, leaf_count, payload_bytes)
    call map_leaf(value%Deta8Q8, leaf_count, payload_bytes)
    call map_leaf(value%Deta9Q8, leaf_count, payload_bytes)
    call map_leaf(value%Qp_inv_Qf, leaf_count, payload_bytes)
    call map_leaf(value%Qs_inv_Qf, leaf_count, payload_bytes)
    call map_leaf(value%eta4Qf, leaf_count, payload_bytes)
    call map_leaf(value%eta5Qf, leaf_count, payload_bytes)
    call map_leaf(value%eta6Qf, leaf_count, payload_bytes)
    call map_leaf(value%eta7Qf, leaf_count, payload_bytes)
    call map_leaf(value%eta8Qf, leaf_count, payload_bytes)
    call map_leaf(value%eta9Qf, leaf_count, payload_bytes)
    call map_leaf(value%Deta4Qf, leaf_count, payload_bytes)
    call map_leaf(value%Deta5Qf, leaf_count, payload_bytes)
    call map_leaf(value%Deta6Qf, leaf_count, payload_bytes)
    call map_leaf(value%Deta7Qf, leaf_count, payload_bytes)
    call map_leaf(value%Deta8Qf, leaf_count, payload_bytes)
    call map_leaf(value%Deta9Qf, leaf_count, payload_bytes)
    call map_leaf(value%Qp_inv_const_Q_4M, leaf_count, payload_bytes)
    call map_leaf(value%Qs_inv_const_Q_4M, leaf_count, payload_bytes)
    call map_leaf(value%eta4_4M, leaf_count, payload_bytes)
    call map_leaf(value%eta5_4M, leaf_count, payload_bytes)
    call map_leaf(value%eta6_4M, leaf_count, payload_bytes)
    call map_leaf(value%eta7_4M, leaf_count, payload_bytes)
    call map_leaf(value%eta8_4M, leaf_count, payload_bytes)
    call map_leaf(value%eta9_4M, leaf_count, payload_bytes)
    call map_leaf(value%Deta4_4M, leaf_count, payload_bytes)
    call map_leaf(value%Deta5_4M, leaf_count, payload_bytes)
    call map_leaf(value%Deta6_4M, leaf_count, payload_bytes)
    call map_leaf(value%Deta7_4M, leaf_count, payload_bytes)
    call map_leaf(value%Deta8_4M, leaf_count, payload_bytes)
    call map_leaf(value%Deta9_4M, leaf_count, payload_bytes)
    call map_leaf(value%Qp_inv_const_Q_8M, leaf_count, payload_bytes)
    call map_leaf(value%Qs_inv_const_Q_8M, leaf_count, payload_bytes)
    call map_leaf(value%eta4_8M, leaf_count, payload_bytes)
    call map_leaf(value%eta5_8M, leaf_count, payload_bytes)
    call map_leaf(value%eta6_8M, leaf_count, payload_bytes)
    call map_leaf(value%eta7_8M, leaf_count, payload_bytes)
    call map_leaf(value%eta8_8M, leaf_count, payload_bytes)
    call map_leaf(value%eta9_8M, leaf_count, payload_bytes)
    call map_leaf(value%Deta4_8M, leaf_count, payload_bytes)
    call map_leaf(value%Deta5_8M, leaf_count, payload_bytes)
    call map_leaf(value%Deta6_8M, leaf_count, payload_bytes)
    call map_leaf(value%Deta7_8M, leaf_count, payload_bytes)
    call map_leaf(value%Deta8_8M, leaf_count, payload_bytes)
    call map_leaf(value%Deta9_8M, leaf_count, payload_bytes)
    call map_leaf(value%Qp_inv_Qf8, leaf_count, payload_bytes)
    call map_leaf(value%Qs_inv_Qf8, leaf_count, payload_bytes)
    call map_leaf(value%eta4Qf8, leaf_count, payload_bytes)
    call map_leaf(value%eta5Qf8, leaf_count, payload_bytes)
    call map_leaf(value%eta6Qf8, leaf_count, payload_bytes)
    call map_leaf(value%eta7Qf8, leaf_count, payload_bytes)
    call map_leaf(value%eta8Qf8, leaf_count, payload_bytes)
    call map_leaf(value%eta9Qf8, leaf_count, payload_bytes)
    call map_leaf(value%Deta4Qf8, leaf_count, payload_bytes)
    call map_leaf(value%Deta5Qf8, leaf_count, payload_bytes)
    call map_leaf(value%Deta6Qf8, leaf_count, payload_bytes)
    call map_leaf(value%Deta7Qf8, leaf_count, payload_bytes)
    call map_leaf(value%Deta8Qf8, leaf_count, payload_bytes)
    call map_leaf(value%Deta9Qf8, leaf_count, payload_bytes)
  end subroutine enter_block_material

  subroutine check_block_material(value, leaf_count, payload_bytes)
    type(block_material), intent(inout) :: value
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    call check_leaf(value%Deta9Qf8, leaf_count, payload_bytes)
    call check_leaf(value%Deta8Qf8, leaf_count, payload_bytes)
    call check_leaf(value%Deta7Qf8, leaf_count, payload_bytes)
    call check_leaf(value%Deta6Qf8, leaf_count, payload_bytes)
    call check_leaf(value%Deta5Qf8, leaf_count, payload_bytes)
    call check_leaf(value%Deta4Qf8, leaf_count, payload_bytes)
    call check_leaf(value%eta9Qf8, leaf_count, payload_bytes)
    call check_leaf(value%eta8Qf8, leaf_count, payload_bytes)
    call check_leaf(value%eta7Qf8, leaf_count, payload_bytes)
    call check_leaf(value%eta6Qf8, leaf_count, payload_bytes)
    call check_leaf(value%eta5Qf8, leaf_count, payload_bytes)
    call check_leaf(value%eta4Qf8, leaf_count, payload_bytes)
    call check_leaf(value%Qs_inv_Qf8, leaf_count, payload_bytes)
    call check_leaf(value%Qp_inv_Qf8, leaf_count, payload_bytes)
    call check_leaf(value%Deta9_8M, leaf_count, payload_bytes)
    call check_leaf(value%Deta8_8M, leaf_count, payload_bytes)
    call check_leaf(value%Deta7_8M, leaf_count, payload_bytes)
    call check_leaf(value%Deta6_8M, leaf_count, payload_bytes)
    call check_leaf(value%Deta5_8M, leaf_count, payload_bytes)
    call check_leaf(value%Deta4_8M, leaf_count, payload_bytes)
    call check_leaf(value%eta9_8M, leaf_count, payload_bytes)
    call check_leaf(value%eta8_8M, leaf_count, payload_bytes)
    call check_leaf(value%eta7_8M, leaf_count, payload_bytes)
    call check_leaf(value%eta6_8M, leaf_count, payload_bytes)
    call check_leaf(value%eta5_8M, leaf_count, payload_bytes)
    call check_leaf(value%eta4_8M, leaf_count, payload_bytes)
    call check_leaf(value%Qs_inv_const_Q_8M, leaf_count, payload_bytes)
    call check_leaf(value%Qp_inv_const_Q_8M, leaf_count, payload_bytes)
    call check_leaf(value%Deta9_4M, leaf_count, payload_bytes)
    call check_leaf(value%Deta8_4M, leaf_count, payload_bytes)
    call check_leaf(value%Deta7_4M, leaf_count, payload_bytes)
    call check_leaf(value%Deta6_4M, leaf_count, payload_bytes)
    call check_leaf(value%Deta5_4M, leaf_count, payload_bytes)
    call check_leaf(value%Deta4_4M, leaf_count, payload_bytes)
    call check_leaf(value%eta9_4M, leaf_count, payload_bytes)
    call check_leaf(value%eta8_4M, leaf_count, payload_bytes)
    call check_leaf(value%eta7_4M, leaf_count, payload_bytes)
    call check_leaf(value%eta6_4M, leaf_count, payload_bytes)
    call check_leaf(value%eta5_4M, leaf_count, payload_bytes)
    call check_leaf(value%eta4_4M, leaf_count, payload_bytes)
    call check_leaf(value%Qs_inv_const_Q_4M, leaf_count, payload_bytes)
    call check_leaf(value%Qp_inv_const_Q_4M, leaf_count, payload_bytes)
    call check_leaf(value%Deta9Qf, leaf_count, payload_bytes)
    call check_leaf(value%Deta8Qf, leaf_count, payload_bytes)
    call check_leaf(value%Deta7Qf, leaf_count, payload_bytes)
    call check_leaf(value%Deta6Qf, leaf_count, payload_bytes)
    call check_leaf(value%Deta5Qf, leaf_count, payload_bytes)
    call check_leaf(value%Deta4Qf, leaf_count, payload_bytes)
    call check_leaf(value%eta9Qf, leaf_count, payload_bytes)
    call check_leaf(value%eta8Qf, leaf_count, payload_bytes)
    call check_leaf(value%eta7Qf, leaf_count, payload_bytes)
    call check_leaf(value%eta6Qf, leaf_count, payload_bytes)
    call check_leaf(value%eta5Qf, leaf_count, payload_bytes)
    call check_leaf(value%eta4Qf, leaf_count, payload_bytes)
    call check_leaf(value%Qs_inv_Qf, leaf_count, payload_bytes)
    call check_leaf(value%Qp_inv_Qf, leaf_count, payload_bytes)
    call check_leaf(value%Deta9Q8, leaf_count, payload_bytes)
    call check_leaf(value%Deta8Q8, leaf_count, payload_bytes)
    call check_leaf(value%Deta7Q8, leaf_count, payload_bytes)
    call check_leaf(value%Deta6Q8, leaf_count, payload_bytes)
    call check_leaf(value%Deta5Q8, leaf_count, payload_bytes)
    call check_leaf(value%Deta4Q8, leaf_count, payload_bytes)
    call check_leaf(value%eta9Q8, leaf_count, payload_bytes)
    call check_leaf(value%eta8Q8, leaf_count, payload_bytes)
    call check_leaf(value%eta7Q8, leaf_count, payload_bytes)
    call check_leaf(value%eta6Q8, leaf_count, payload_bytes)
    call check_leaf(value%eta5Q8, leaf_count, payload_bytes)
    call check_leaf(value%eta4Q8, leaf_count, payload_bytes)
    call check_leaf(value%Qs_inv_Q8, leaf_count, payload_bytes)
    call check_leaf(value%Qp_inv_Q8, leaf_count, payload_bytes)
    call check_leaf(value%Deta9Q, leaf_count, payload_bytes)
    call check_leaf(value%Deta8Q, leaf_count, payload_bytes)
    call check_leaf(value%Deta7Q, leaf_count, payload_bytes)
    call check_leaf(value%Deta6Q, leaf_count, payload_bytes)
    call check_leaf(value%Deta5Q, leaf_count, payload_bytes)
    call check_leaf(value%Deta4Q, leaf_count, payload_bytes)
    call check_leaf(value%eta9Q, leaf_count, payload_bytes)
    call check_leaf(value%eta8Q, leaf_count, payload_bytes)
    call check_leaf(value%eta7Q, leaf_count, payload_bytes)
    call check_leaf(value%eta6Q, leaf_count, payload_bytes)
    call check_leaf(value%eta5Q, leaf_count, payload_bytes)
    call check_leaf(value%eta4Q, leaf_count, payload_bytes)
    call check_leaf(value%Qs_inv_Q, leaf_count, payload_bytes)
    call check_leaf(value%Qp_inv_Q, leaf_count, payload_bytes)
    call check_leaf(value%Deta9, leaf_count, payload_bytes)
    call check_leaf(value%Deta8, leaf_count, payload_bytes)
    call check_leaf(value%Deta7, leaf_count, payload_bytes)
    call check_leaf(value%Deta6, leaf_count, payload_bytes)
    call check_leaf(value%Deta5, leaf_count, payload_bytes)
    call check_leaf(value%Deta4, leaf_count, payload_bytes)
    call check_leaf(value%eta9, leaf_count, payload_bytes)
    call check_leaf(value%eta8, leaf_count, payload_bytes)
    call check_leaf(value%eta7, leaf_count, payload_bytes)
    call check_leaf(value%eta6, leaf_count, payload_bytes)
    call check_leaf(value%eta5, leaf_count, payload_bytes)
    call check_leaf(value%eta4, leaf_count, payload_bytes)
    call check_leaf(value%Qs_inv, leaf_count, payload_bytes)
    call check_leaf(value%Qp_inv, leaf_count, payload_bytes)
    call check_leaf(value%M, leaf_count, payload_bytes)
  end subroutine check_block_material

  subroutine exit_block_material(value, leaf_count, payload_bytes)
    type(block_material), intent(inout) :: value
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    call unmap_leaf(value%Deta9Qf8, leaf_count, payload_bytes)
    call unmap_leaf(value%Deta8Qf8, leaf_count, payload_bytes)
    call unmap_leaf(value%Deta7Qf8, leaf_count, payload_bytes)
    call unmap_leaf(value%Deta6Qf8, leaf_count, payload_bytes)
    call unmap_leaf(value%Deta5Qf8, leaf_count, payload_bytes)
    call unmap_leaf(value%Deta4Qf8, leaf_count, payload_bytes)
    call unmap_leaf(value%eta9Qf8, leaf_count, payload_bytes)
    call unmap_leaf(value%eta8Qf8, leaf_count, payload_bytes)
    call unmap_leaf(value%eta7Qf8, leaf_count, payload_bytes)
    call unmap_leaf(value%eta6Qf8, leaf_count, payload_bytes)
    call unmap_leaf(value%eta5Qf8, leaf_count, payload_bytes)
    call unmap_leaf(value%eta4Qf8, leaf_count, payload_bytes)
    call unmap_leaf(value%Qs_inv_Qf8, leaf_count, payload_bytes)
    call unmap_leaf(value%Qp_inv_Qf8, leaf_count, payload_bytes)
    call unmap_leaf(value%Deta9_8M, leaf_count, payload_bytes)
    call unmap_leaf(value%Deta8_8M, leaf_count, payload_bytes)
    call unmap_leaf(value%Deta7_8M, leaf_count, payload_bytes)
    call unmap_leaf(value%Deta6_8M, leaf_count, payload_bytes)
    call unmap_leaf(value%Deta5_8M, leaf_count, payload_bytes)
    call unmap_leaf(value%Deta4_8M, leaf_count, payload_bytes)
    call unmap_leaf(value%eta9_8M, leaf_count, payload_bytes)
    call unmap_leaf(value%eta8_8M, leaf_count, payload_bytes)
    call unmap_leaf(value%eta7_8M, leaf_count, payload_bytes)
    call unmap_leaf(value%eta6_8M, leaf_count, payload_bytes)
    call unmap_leaf(value%eta5_8M, leaf_count, payload_bytes)
    call unmap_leaf(value%eta4_8M, leaf_count, payload_bytes)
    call unmap_leaf(value%Qs_inv_const_Q_8M, leaf_count, payload_bytes)
    call unmap_leaf(value%Qp_inv_const_Q_8M, leaf_count, payload_bytes)
    call unmap_leaf(value%Deta9_4M, leaf_count, payload_bytes)
    call unmap_leaf(value%Deta8_4M, leaf_count, payload_bytes)
    call unmap_leaf(value%Deta7_4M, leaf_count, payload_bytes)
    call unmap_leaf(value%Deta6_4M, leaf_count, payload_bytes)
    call unmap_leaf(value%Deta5_4M, leaf_count, payload_bytes)
    call unmap_leaf(value%Deta4_4M, leaf_count, payload_bytes)
    call unmap_leaf(value%eta9_4M, leaf_count, payload_bytes)
    call unmap_leaf(value%eta8_4M, leaf_count, payload_bytes)
    call unmap_leaf(value%eta7_4M, leaf_count, payload_bytes)
    call unmap_leaf(value%eta6_4M, leaf_count, payload_bytes)
    call unmap_leaf(value%eta5_4M, leaf_count, payload_bytes)
    call unmap_leaf(value%eta4_4M, leaf_count, payload_bytes)
    call unmap_leaf(value%Qs_inv_const_Q_4M, leaf_count, payload_bytes)
    call unmap_leaf(value%Qp_inv_const_Q_4M, leaf_count, payload_bytes)
    call unmap_leaf(value%Deta9Qf, leaf_count, payload_bytes)
    call unmap_leaf(value%Deta8Qf, leaf_count, payload_bytes)
    call unmap_leaf(value%Deta7Qf, leaf_count, payload_bytes)
    call unmap_leaf(value%Deta6Qf, leaf_count, payload_bytes)
    call unmap_leaf(value%Deta5Qf, leaf_count, payload_bytes)
    call unmap_leaf(value%Deta4Qf, leaf_count, payload_bytes)
    call unmap_leaf(value%eta9Qf, leaf_count, payload_bytes)
    call unmap_leaf(value%eta8Qf, leaf_count, payload_bytes)
    call unmap_leaf(value%eta7Qf, leaf_count, payload_bytes)
    call unmap_leaf(value%eta6Qf, leaf_count, payload_bytes)
    call unmap_leaf(value%eta5Qf, leaf_count, payload_bytes)
    call unmap_leaf(value%eta4Qf, leaf_count, payload_bytes)
    call unmap_leaf(value%Qs_inv_Qf, leaf_count, payload_bytes)
    call unmap_leaf(value%Qp_inv_Qf, leaf_count, payload_bytes)
    call unmap_leaf(value%Deta9Q8, leaf_count, payload_bytes)
    call unmap_leaf(value%Deta8Q8, leaf_count, payload_bytes)
    call unmap_leaf(value%Deta7Q8, leaf_count, payload_bytes)
    call unmap_leaf(value%Deta6Q8, leaf_count, payload_bytes)
    call unmap_leaf(value%Deta5Q8, leaf_count, payload_bytes)
    call unmap_leaf(value%Deta4Q8, leaf_count, payload_bytes)
    call unmap_leaf(value%eta9Q8, leaf_count, payload_bytes)
    call unmap_leaf(value%eta8Q8, leaf_count, payload_bytes)
    call unmap_leaf(value%eta7Q8, leaf_count, payload_bytes)
    call unmap_leaf(value%eta6Q8, leaf_count, payload_bytes)
    call unmap_leaf(value%eta5Q8, leaf_count, payload_bytes)
    call unmap_leaf(value%eta4Q8, leaf_count, payload_bytes)
    call unmap_leaf(value%Qs_inv_Q8, leaf_count, payload_bytes)
    call unmap_leaf(value%Qp_inv_Q8, leaf_count, payload_bytes)
    call unmap_leaf(value%Deta9Q, leaf_count, payload_bytes)
    call unmap_leaf(value%Deta8Q, leaf_count, payload_bytes)
    call unmap_leaf(value%Deta7Q, leaf_count, payload_bytes)
    call unmap_leaf(value%Deta6Q, leaf_count, payload_bytes)
    call unmap_leaf(value%Deta5Q, leaf_count, payload_bytes)
    call unmap_leaf(value%Deta4Q, leaf_count, payload_bytes)
    call unmap_leaf(value%eta9Q, leaf_count, payload_bytes)
    call unmap_leaf(value%eta8Q, leaf_count, payload_bytes)
    call unmap_leaf(value%eta7Q, leaf_count, payload_bytes)
    call unmap_leaf(value%eta6Q, leaf_count, payload_bytes)
    call unmap_leaf(value%eta5Q, leaf_count, payload_bytes)
    call unmap_leaf(value%eta4Q, leaf_count, payload_bytes)
    call unmap_leaf(value%Qs_inv_Q, leaf_count, payload_bytes)
    call unmap_leaf(value%Qp_inv_Q, leaf_count, payload_bytes)
    call unmap_leaf(value%Deta9, leaf_count, payload_bytes)
    call unmap_leaf(value%Deta8, leaf_count, payload_bytes)
    call unmap_leaf(value%Deta7, leaf_count, payload_bytes)
    call unmap_leaf(value%Deta6, leaf_count, payload_bytes)
    call unmap_leaf(value%Deta5, leaf_count, payload_bytes)
    call unmap_leaf(value%Deta4, leaf_count, payload_bytes)
    call unmap_leaf(value%eta9, leaf_count, payload_bytes)
    call unmap_leaf(value%eta8, leaf_count, payload_bytes)
    call unmap_leaf(value%eta7, leaf_count, payload_bytes)
    call unmap_leaf(value%eta6, leaf_count, payload_bytes)
    call unmap_leaf(value%eta5, leaf_count, payload_bytes)
    call unmap_leaf(value%eta4, leaf_count, payload_bytes)
    call unmap_leaf(value%Qs_inv, leaf_count, payload_bytes)
    call unmap_leaf(value%Qp_inv, leaf_count, payload_bytes)
    call unmap_leaf(value%M, leaf_count, payload_bytes)
  end subroutine exit_block_material

  subroutine update_host_block_material(value, leaf_count, payload_bytes)
    type(block_material), intent(inout) :: value
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    call update_host_leaf(value%eta4, leaf_count, payload_bytes)
    call update_host_leaf(value%eta5, leaf_count, payload_bytes)
    call update_host_leaf(value%eta6, leaf_count, payload_bytes)
    call update_host_leaf(value%eta7, leaf_count, payload_bytes)
    call update_host_leaf(value%eta8, leaf_count, payload_bytes)
    call update_host_leaf(value%eta9, leaf_count, payload_bytes)
    call update_host_leaf(value%Deta4, leaf_count, payload_bytes)
    call update_host_leaf(value%Deta5, leaf_count, payload_bytes)
    call update_host_leaf(value%Deta6, leaf_count, payload_bytes)
    call update_host_leaf(value%Deta7, leaf_count, payload_bytes)
    call update_host_leaf(value%Deta8, leaf_count, payload_bytes)
    call update_host_leaf(value%Deta9, leaf_count, payload_bytes)
    call update_host_leaf(value%eta4Q, leaf_count, payload_bytes)
    call update_host_leaf(value%eta5Q, leaf_count, payload_bytes)
    call update_host_leaf(value%eta6Q, leaf_count, payload_bytes)
    call update_host_leaf(value%eta7Q, leaf_count, payload_bytes)
    call update_host_leaf(value%eta8Q, leaf_count, payload_bytes)
    call update_host_leaf(value%eta9Q, leaf_count, payload_bytes)
    call update_host_leaf(value%Deta4Q, leaf_count, payload_bytes)
    call update_host_leaf(value%Deta5Q, leaf_count, payload_bytes)
    call update_host_leaf(value%Deta6Q, leaf_count, payload_bytes)
    call update_host_leaf(value%Deta7Q, leaf_count, payload_bytes)
    call update_host_leaf(value%Deta8Q, leaf_count, payload_bytes)
    call update_host_leaf(value%Deta9Q, leaf_count, payload_bytes)
    call update_host_leaf(value%eta4Q8, leaf_count, payload_bytes)
    call update_host_leaf(value%eta5Q8, leaf_count, payload_bytes)
    call update_host_leaf(value%eta6Q8, leaf_count, payload_bytes)
    call update_host_leaf(value%eta7Q8, leaf_count, payload_bytes)
    call update_host_leaf(value%eta8Q8, leaf_count, payload_bytes)
    call update_host_leaf(value%eta9Q8, leaf_count, payload_bytes)
    call update_host_leaf(value%Deta4Q8, leaf_count, payload_bytes)
    call update_host_leaf(value%Deta5Q8, leaf_count, payload_bytes)
    call update_host_leaf(value%Deta6Q8, leaf_count, payload_bytes)
    call update_host_leaf(value%Deta7Q8, leaf_count, payload_bytes)
    call update_host_leaf(value%Deta8Q8, leaf_count, payload_bytes)
    call update_host_leaf(value%Deta9Q8, leaf_count, payload_bytes)
    call update_host_leaf(value%eta4Qf, leaf_count, payload_bytes)
    call update_host_leaf(value%eta5Qf, leaf_count, payload_bytes)
    call update_host_leaf(value%eta6Qf, leaf_count, payload_bytes)
    call update_host_leaf(value%eta7Qf, leaf_count, payload_bytes)
    call update_host_leaf(value%eta8Qf, leaf_count, payload_bytes)
    call update_host_leaf(value%eta9Qf, leaf_count, payload_bytes)
    call update_host_leaf(value%Deta4Qf, leaf_count, payload_bytes)
    call update_host_leaf(value%Deta5Qf, leaf_count, payload_bytes)
    call update_host_leaf(value%Deta6Qf, leaf_count, payload_bytes)
    call update_host_leaf(value%Deta7Qf, leaf_count, payload_bytes)
    call update_host_leaf(value%Deta8Qf, leaf_count, payload_bytes)
    call update_host_leaf(value%Deta9Qf, leaf_count, payload_bytes)
    call update_host_leaf(value%eta4_4M, leaf_count, payload_bytes)
    call update_host_leaf(value%eta5_4M, leaf_count, payload_bytes)
    call update_host_leaf(value%eta6_4M, leaf_count, payload_bytes)
    call update_host_leaf(value%eta7_4M, leaf_count, payload_bytes)
    call update_host_leaf(value%eta8_4M, leaf_count, payload_bytes)
    call update_host_leaf(value%eta9_4M, leaf_count, payload_bytes)
    call update_host_leaf(value%Deta4_4M, leaf_count, payload_bytes)
    call update_host_leaf(value%Deta5_4M, leaf_count, payload_bytes)
    call update_host_leaf(value%Deta6_4M, leaf_count, payload_bytes)
    call update_host_leaf(value%Deta7_4M, leaf_count, payload_bytes)
    call update_host_leaf(value%Deta8_4M, leaf_count, payload_bytes)
    call update_host_leaf(value%Deta9_4M, leaf_count, payload_bytes)
    call update_host_leaf(value%eta4_8M, leaf_count, payload_bytes)
    call update_host_leaf(value%eta5_8M, leaf_count, payload_bytes)
    call update_host_leaf(value%eta6_8M, leaf_count, payload_bytes)
    call update_host_leaf(value%eta7_8M, leaf_count, payload_bytes)
    call update_host_leaf(value%eta8_8M, leaf_count, payload_bytes)
    call update_host_leaf(value%eta9_8M, leaf_count, payload_bytes)
    call update_host_leaf(value%Deta4_8M, leaf_count, payload_bytes)
    call update_host_leaf(value%Deta5_8M, leaf_count, payload_bytes)
    call update_host_leaf(value%Deta6_8M, leaf_count, payload_bytes)
    call update_host_leaf(value%Deta7_8M, leaf_count, payload_bytes)
    call update_host_leaf(value%Deta8_8M, leaf_count, payload_bytes)
    call update_host_leaf(value%Deta9_8M, leaf_count, payload_bytes)
    call update_host_leaf(value%eta4Qf8, leaf_count, payload_bytes)
    call update_host_leaf(value%eta5Qf8, leaf_count, payload_bytes)
    call update_host_leaf(value%eta6Qf8, leaf_count, payload_bytes)
    call update_host_leaf(value%eta7Qf8, leaf_count, payload_bytes)
    call update_host_leaf(value%eta8Qf8, leaf_count, payload_bytes)
    call update_host_leaf(value%eta9Qf8, leaf_count, payload_bytes)
    call update_host_leaf(value%Deta4Qf8, leaf_count, payload_bytes)
    call update_host_leaf(value%Deta5Qf8, leaf_count, payload_bytes)
    call update_host_leaf(value%Deta6Qf8, leaf_count, payload_bytes)
    call update_host_leaf(value%Deta7Qf8, leaf_count, payload_bytes)
    call update_host_leaf(value%Deta8Qf8, leaf_count, payload_bytes)
    call update_host_leaf(value%Deta9Qf8, leaf_count, payload_bytes)
  end subroutine update_host_block_material

  subroutine enter_block_plastic(value, leaf_count, payload_bytes)
    type(block_plastic), intent(inout) :: value
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    call map_leaf(value%P, leaf_count, payload_bytes)
  end subroutine enter_block_plastic

  subroutine check_block_plastic(value, leaf_count, payload_bytes)
    type(block_plastic), intent(inout) :: value
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    call check_leaf(value%P, leaf_count, payload_bytes)
  end subroutine check_block_plastic

  subroutine exit_block_plastic(value, leaf_count, payload_bytes)
    type(block_plastic), intent(inout) :: value
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    call unmap_leaf(value%P, leaf_count, payload_bytes)
  end subroutine exit_block_plastic

  subroutine update_host_block_plastic(value, leaf_count, payload_bytes)
    type(block_plastic), intent(inout) :: value
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    call update_host_leaf(value%P, leaf_count, payload_bytes)
  end subroutine update_host_block_plastic

  subroutine enter_block_fields(value, leaf_count, payload_bytes)
    type(block_fields), intent(inout) :: value
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    call map_leaf(value%F, leaf_count, payload_bytes)
    call map_leaf(value%DF, leaf_count, payload_bytes)
  end subroutine enter_block_fields

  subroutine check_block_fields(value, leaf_count, payload_bytes)
    type(block_fields), intent(inout) :: value
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    call check_leaf(value%DF, leaf_count, payload_bytes)
    call check_leaf(value%F, leaf_count, payload_bytes)
  end subroutine check_block_fields

  subroutine exit_block_fields(value, leaf_count, payload_bytes)
    type(block_fields), intent(inout) :: value
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    call unmap_leaf(value%DF, leaf_count, payload_bytes)
    call unmap_leaf(value%F, leaf_count, payload_bytes)
  end subroutine exit_block_fields

  subroutine update_host_block_fields(value, leaf_count, payload_bytes)
    type(block_fields), intent(inout) :: value
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    call update_host_leaf(value%F, leaf_count, payload_bytes)
    call update_host_leaf(value%DF, leaf_count, payload_bytes)
  end subroutine update_host_block_fields

  subroutine enter_block_boundary(value, leaf_count, payload_bytes)
    type(block_boundary), intent(inout) :: value
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    call map_leaf(value%X, leaf_count, payload_bytes)
    call map_leaf(value%M, leaf_count, payload_bytes)
    call map_leaf(value%n_l, leaf_count, payload_bytes)
    call map_leaf(value%n_m, leaf_count, payload_bytes)
    call map_leaf(value%n_n, leaf_count, payload_bytes)
    call map_leaf(value%F, leaf_count, payload_bytes)
    call map_leaf(value%DF, leaf_count, payload_bytes)
    call map_leaf(value%Fopp, leaf_count, payload_bytes)
    call map_leaf(value%Mopp, leaf_count, payload_bytes)
    call map_leaf(value%U, leaf_count, payload_bytes)
    call map_leaf(value%DU, leaf_count, payload_bytes)
  end subroutine enter_block_boundary

  subroutine check_block_boundary(value, leaf_count, payload_bytes)
    type(block_boundary), intent(inout) :: value
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    call check_leaf(value%DU, leaf_count, payload_bytes)
    call check_leaf(value%U, leaf_count, payload_bytes)
    call check_leaf(value%Mopp, leaf_count, payload_bytes)
    call check_leaf(value%Fopp, leaf_count, payload_bytes)
    call check_leaf(value%DF, leaf_count, payload_bytes)
    call check_leaf(value%F, leaf_count, payload_bytes)
    call check_leaf(value%n_n, leaf_count, payload_bytes)
    call check_leaf(value%n_m, leaf_count, payload_bytes)
    call check_leaf(value%n_l, leaf_count, payload_bytes)
    call check_leaf(value%M, leaf_count, payload_bytes)
    call check_leaf(value%X, leaf_count, payload_bytes)
  end subroutine check_block_boundary

  subroutine exit_block_boundary(value, leaf_count, payload_bytes)
    type(block_boundary), intent(inout) :: value
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    call unmap_leaf(value%DU, leaf_count, payload_bytes)
    call unmap_leaf(value%U, leaf_count, payload_bytes)
    call unmap_leaf(value%Mopp, leaf_count, payload_bytes)
    call unmap_leaf(value%Fopp, leaf_count, payload_bytes)
    call unmap_leaf(value%DF, leaf_count, payload_bytes)
    call unmap_leaf(value%F, leaf_count, payload_bytes)
    call unmap_leaf(value%n_n, leaf_count, payload_bytes)
    call unmap_leaf(value%n_m, leaf_count, payload_bytes)
    call unmap_leaf(value%n_l, leaf_count, payload_bytes)
    call unmap_leaf(value%M, leaf_count, payload_bytes)
    call unmap_leaf(value%X, leaf_count, payload_bytes)
  end subroutine exit_block_boundary

  subroutine update_host_block_boundary(value, leaf_count, payload_bytes)
    type(block_boundary), intent(inout) :: value
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    call update_host_leaf(value%X, leaf_count, payload_bytes)
    call update_host_leaf(value%M, leaf_count, payload_bytes)
    call update_host_leaf(value%n_l, leaf_count, payload_bytes)
    call update_host_leaf(value%n_m, leaf_count, payload_bytes)
    call update_host_leaf(value%n_n, leaf_count, payload_bytes)
    call update_host_leaf(value%F, leaf_count, payload_bytes)
    call update_host_leaf(value%DF, leaf_count, payload_bytes)
    call update_host_leaf(value%Fopp, leaf_count, payload_bytes)
    call update_host_leaf(value%Mopp, leaf_count, payload_bytes)
    call update_host_leaf(value%U, leaf_count, payload_bytes)
    call update_host_leaf(value%DU, leaf_count, payload_bytes)
  end subroutine update_host_block_boundary

  subroutine enter_moment_tensor(value, leaf_count, payload_bytes)
    type(moment_tensor), intent(inout) :: value
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    call map_leaf(value%source_type, leaf_count, payload_bytes)
    call map_leaf(value%mXX, leaf_count, payload_bytes)
    call map_leaf(value%mXY, leaf_count, payload_bytes)
    call map_leaf(value%mXZ, leaf_count, payload_bytes)
    call map_leaf(value%mYY, leaf_count, payload_bytes)
    call map_leaf(value%mYZ, leaf_count, payload_bytes)
    call map_leaf(value%mZZ, leaf_count, payload_bytes)
    call map_leaf(value%location_x, leaf_count, payload_bytes)
    call map_leaf(value%location_y, leaf_count, payload_bytes)
    call map_leaf(value%location_z, leaf_count, payload_bytes)
    call map_leaf(value%near_x, leaf_count, payload_bytes)
    call map_leaf(value%near_y, leaf_count, payload_bytes)
    call map_leaf(value%near_z, leaf_count, payload_bytes)
    call map_leaf(value%alpha, leaf_count, payload_bytes)
    call map_leaf(value%near_phys_x, leaf_count, payload_bytes)
    call map_leaf(value%near_phys_y, leaf_count, payload_bytes)
    call map_leaf(value%near_phys_z, leaf_count, payload_bytes)
    call map_leaf(value%exact, leaf_count, payload_bytes)
    call map_leaf(value%duration, leaf_count, payload_bytes)
    call map_leaf(value%t_init, leaf_count, payload_bytes)
  end subroutine enter_moment_tensor

  subroutine check_moment_tensor(value, leaf_count, payload_bytes)
    type(moment_tensor), intent(inout) :: value
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    call check_leaf(value%t_init, leaf_count, payload_bytes)
    call check_leaf(value%duration, leaf_count, payload_bytes)
    call check_leaf(value%exact, leaf_count, payload_bytes)
    call check_leaf(value%near_phys_z, leaf_count, payload_bytes)
    call check_leaf(value%near_phys_y, leaf_count, payload_bytes)
    call check_leaf(value%near_phys_x, leaf_count, payload_bytes)
    call check_leaf(value%alpha, leaf_count, payload_bytes)
    call check_leaf(value%near_z, leaf_count, payload_bytes)
    call check_leaf(value%near_y, leaf_count, payload_bytes)
    call check_leaf(value%near_x, leaf_count, payload_bytes)
    call check_leaf(value%location_z, leaf_count, payload_bytes)
    call check_leaf(value%location_y, leaf_count, payload_bytes)
    call check_leaf(value%location_x, leaf_count, payload_bytes)
    call check_leaf(value%mZZ, leaf_count, payload_bytes)
    call check_leaf(value%mYZ, leaf_count, payload_bytes)
    call check_leaf(value%mYY, leaf_count, payload_bytes)
    call check_leaf(value%mXZ, leaf_count, payload_bytes)
    call check_leaf(value%mXY, leaf_count, payload_bytes)
    call check_leaf(value%mXX, leaf_count, payload_bytes)
    call check_leaf(value%source_type, leaf_count, payload_bytes)
  end subroutine check_moment_tensor

  subroutine exit_moment_tensor(value, leaf_count, payload_bytes)
    type(moment_tensor), intent(inout) :: value
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    call unmap_leaf(value%t_init, leaf_count, payload_bytes)
    call unmap_leaf(value%duration, leaf_count, payload_bytes)
    call unmap_leaf(value%exact, leaf_count, payload_bytes)
    call unmap_leaf(value%near_phys_z, leaf_count, payload_bytes)
    call unmap_leaf(value%near_phys_y, leaf_count, payload_bytes)
    call unmap_leaf(value%near_phys_x, leaf_count, payload_bytes)
    call unmap_leaf(value%alpha, leaf_count, payload_bytes)
    call unmap_leaf(value%near_z, leaf_count, payload_bytes)
    call unmap_leaf(value%near_y, leaf_count, payload_bytes)
    call unmap_leaf(value%near_x, leaf_count, payload_bytes)
    call unmap_leaf(value%location_z, leaf_count, payload_bytes)
    call unmap_leaf(value%location_y, leaf_count, payload_bytes)
    call unmap_leaf(value%location_x, leaf_count, payload_bytes)
    call unmap_leaf(value%mZZ, leaf_count, payload_bytes)
    call unmap_leaf(value%mYZ, leaf_count, payload_bytes)
    call unmap_leaf(value%mYY, leaf_count, payload_bytes)
    call unmap_leaf(value%mXZ, leaf_count, payload_bytes)
    call unmap_leaf(value%mXY, leaf_count, payload_bytes)
    call unmap_leaf(value%mXX, leaf_count, payload_bytes)
    call unmap_leaf(value%source_type, leaf_count, payload_bytes)
  end subroutine exit_moment_tensor

  subroutine enter_block_pml(value, leaf_count, payload_bytes)
    type(block_pml), intent(inout) :: value
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    call map_leaf(value%Q, leaf_count, payload_bytes)
    call map_leaf(value%DQ, leaf_count, payload_bytes)
  end subroutine enter_block_pml

  subroutine check_block_pml(value, leaf_count, payload_bytes)
    type(block_pml), intent(inout) :: value
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    call check_leaf(value%DQ, leaf_count, payload_bytes)
    call check_leaf(value%Q, leaf_count, payload_bytes)
  end subroutine check_block_pml

  subroutine exit_block_pml(value, leaf_count, payload_bytes)
    type(block_pml), intent(inout) :: value
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    call unmap_leaf(value%DQ, leaf_count, payload_bytes)
    call unmap_leaf(value%Q, leaf_count, payload_bytes)
  end subroutine exit_block_pml

  subroutine update_host_block_pml(value, leaf_count, payload_bytes)
    type(block_pml), intent(inout) :: value
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    call update_host_leaf(value%Q, leaf_count, payload_bytes)
    call update_host_leaf(value%DQ, leaf_count, payload_bytes)
  end subroutine update_host_block_pml

  subroutine enter_block_type(value, leaf_count, payload_bytes)
    type(block_type), intent(inout) :: value
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    call map_leaf(value%work_boundary_q, leaf_count, payload_bytes)
    call map_leaf(value%work_boundary_r, leaf_count, payload_bytes)
    call map_leaf(value%work_boundary_s, leaf_count, payload_bytes)
  end subroutine enter_block_type

  subroutine check_block_type(value, leaf_count, payload_bytes)
    type(block_type), intent(inout) :: value
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    call check_leaf(value%work_boundary_s, leaf_count, payload_bytes)
    call check_leaf(value%work_boundary_r, leaf_count, payload_bytes)
    call check_leaf(value%work_boundary_q, leaf_count, payload_bytes)
  end subroutine check_block_type

  subroutine exit_block_type(value, leaf_count, payload_bytes)
    type(block_type), intent(inout) :: value
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    call unmap_leaf(value%work_boundary_s, leaf_count, payload_bytes)
    call unmap_leaf(value%work_boundary_r, leaf_count, payload_bytes)
    call unmap_leaf(value%work_boundary_q, leaf_count, payload_bytes)
  end subroutine exit_block_type

  subroutine update_host_block_type(value, leaf_count, payload_bytes)
    type(block_type), intent(inout) :: value
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    call update_host_leaf(value%work_boundary_q, leaf_count, payload_bytes)
    call update_host_leaf(value%work_boundary_r, leaf_count, payload_bytes)
    call update_host_leaf(value%work_boundary_s, leaf_count, payload_bytes)
  end subroutine update_host_block_type

  subroutine enter_iface_type(value, leaf_count, payload_bytes)
    type(iface_type), intent(inout) :: value
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    call map_leaf(value%V, leaf_count, payload_bytes)
    call map_leaf(value%DV, leaf_count, payload_bytes)
    call map_leaf(value%T, leaf_count, payload_bytes)
    call map_leaf(value%S, leaf_count, payload_bytes)
    call map_leaf(value%DS, leaf_count, payload_bytes)
    call map_leaf(value%W, leaf_count, payload_bytes)
    call map_leaf(value%DW, leaf_count, payload_bytes)
    call map_leaf(value%Svel, leaf_count, payload_bytes)
    call map_leaf(value%trup, leaf_count, payload_bytes)
    call map_leaf(value%work_F, leaf_count, payload_bytes)
    call map_leaf(value%work_G, leaf_count, payload_bytes)
    call map_leaf(value%work_u_rotated, leaf_count, payload_bytes)
    call map_leaf(value%work_v_rotated, leaf_count, payload_bytes)
    call map_leaf(value%work_u_hat, leaf_count, payload_bytes)
    call map_leaf(value%work_v_hat, leaf_count, payload_bytes)
  end subroutine enter_iface_type

  subroutine check_iface_type(value, leaf_count, payload_bytes)
    type(iface_type), intent(inout) :: value
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    call check_leaf(value%work_v_hat, leaf_count, payload_bytes)
    call check_leaf(value%work_u_hat, leaf_count, payload_bytes)
    call check_leaf(value%work_v_rotated, leaf_count, payload_bytes)
    call check_leaf(value%work_u_rotated, leaf_count, payload_bytes)
    call check_leaf(value%work_G, leaf_count, payload_bytes)
    call check_leaf(value%work_F, leaf_count, payload_bytes)
    call check_leaf(value%trup, leaf_count, payload_bytes)
    call check_leaf(value%Svel, leaf_count, payload_bytes)
    call check_leaf(value%DW, leaf_count, payload_bytes)
    call check_leaf(value%W, leaf_count, payload_bytes)
    call check_leaf(value%DS, leaf_count, payload_bytes)
    call check_leaf(value%S, leaf_count, payload_bytes)
    call check_leaf(value%T, leaf_count, payload_bytes)
    call check_leaf(value%DV, leaf_count, payload_bytes)
    call check_leaf(value%V, leaf_count, payload_bytes)
  end subroutine check_iface_type

  subroutine exit_iface_type(value, leaf_count, payload_bytes)
    type(iface_type), intent(inout) :: value
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    call unmap_leaf(value%work_v_hat, leaf_count, payload_bytes)
    call unmap_leaf(value%work_u_hat, leaf_count, payload_bytes)
    call unmap_leaf(value%work_v_rotated, leaf_count, payload_bytes)
    call unmap_leaf(value%work_u_rotated, leaf_count, payload_bytes)
    call unmap_leaf(value%work_G, leaf_count, payload_bytes)
    call unmap_leaf(value%work_F, leaf_count, payload_bytes)
    call unmap_leaf(value%trup, leaf_count, payload_bytes)
    call unmap_leaf(value%Svel, leaf_count, payload_bytes)
    call unmap_leaf(value%DW, leaf_count, payload_bytes)
    call unmap_leaf(value%W, leaf_count, payload_bytes)
    call unmap_leaf(value%DS, leaf_count, payload_bytes)
    call unmap_leaf(value%S, leaf_count, payload_bytes)
    call unmap_leaf(value%T, leaf_count, payload_bytes)
    call unmap_leaf(value%DV, leaf_count, payload_bytes)
    call unmap_leaf(value%V, leaf_count, payload_bytes)
  end subroutine exit_iface_type

  subroutine update_host_iface_type(value, leaf_count, payload_bytes)
    type(iface_type), intent(inout) :: value
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    call update_host_leaf(value%V, leaf_count, payload_bytes)
    call update_host_leaf(value%DV, leaf_count, payload_bytes)
    call update_host_leaf(value%T, leaf_count, payload_bytes)
    call update_host_leaf(value%S, leaf_count, payload_bytes)
    call update_host_leaf(value%DS, leaf_count, payload_bytes)
    call update_host_leaf(value%W, leaf_count, payload_bytes)
    call update_host_leaf(value%DW, leaf_count, payload_bytes)
    call update_host_leaf(value%Svel, leaf_count, payload_bytes)
    call update_host_leaf(value%trup, leaf_count, payload_bytes)
    call update_host_leaf(value%work_F, leaf_count, payload_bytes)
    call update_host_leaf(value%work_G, leaf_count, payload_bytes)
    call update_host_leaf(value%work_u_rotated, leaf_count, payload_bytes)
    call update_host_leaf(value%work_v_rotated, leaf_count, payload_bytes)
    call update_host_leaf(value%work_u_hat, leaf_count, payload_bytes)
    call update_host_leaf(value%work_v_hat, leaf_count, payload_bytes)
  end subroutine update_host_iface_type


  subroutine account_leaf(element_count, bits, leaf_count, payload_bytes)
    integer, intent(in) :: element_count, bits
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    leaf_count = leaf_count + 1
    payload_bytes = payload_bytes + int(element_count,int64)*int(bits/8,int64)
  end subroutine account_leaf

  subroutine map_real_1(value, leaf_count, payload_bytes)
    real(kind=wp), allocatable, intent(inout) :: value(:)
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    if (.not.allocated(value)) return
    if (size(value) == 0) return
    call acc_copyin(value, int(size(value),8)*int(storage_size(0.0_wp)/8,8))
    if (.not.acc_is_present(value, int(size(value),8)*int(storage_size(0.0_wp)/8,8))) call device_data_error('RUN-DEVICE-DATA-008','Real rank-1 leaf is absent after copyin.')
    call account_leaf(size(value), storage_size(0.0_wp), leaf_count, payload_bytes)
  end subroutine
  subroutine map_real_2(value, leaf_count, payload_bytes)
    real(kind=wp), allocatable, intent(inout) :: value(:,:)
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    if (.not.allocated(value)) return
    if (size(value) == 0) return
    call acc_copyin(value, int(size(value),8)*int(storage_size(0.0_wp)/8,8))
    if (.not.acc_is_present(value, int(size(value),8)*int(storage_size(0.0_wp)/8,8))) call device_data_error('RUN-DEVICE-DATA-008','Real rank-2 leaf is absent after copyin.')
    call account_leaf(size(value), storage_size(0.0_wp), leaf_count, payload_bytes)
  end subroutine
  subroutine map_real_3(value, leaf_count, payload_bytes)
    real(kind=wp), allocatable, intent(inout) :: value(:,:,:)
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    if (.not.allocated(value)) return
    if (size(value) == 0) return
    call acc_copyin(value, int(size(value),8)*int(storage_size(0.0_wp)/8,8))
    if (.not.acc_is_present(value, int(size(value),8)*int(storage_size(0.0_wp)/8,8))) call device_data_error('RUN-DEVICE-DATA-008','Real rank-3 leaf is absent after copyin.')
    call account_leaf(size(value), storage_size(0.0_wp), leaf_count, payload_bytes)
  end subroutine
  subroutine map_real_4(value, leaf_count, payload_bytes)
    real(kind=wp), allocatable, intent(inout) :: value(:,:,:,:)
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    if (.not.allocated(value)) return
    if (size(value) == 0) return
    call acc_copyin(value, int(size(value),8)*int(storage_size(0.0_wp)/8,8))
    if (.not.acc_is_present(value, int(size(value),8)*int(storage_size(0.0_wp)/8,8))) call device_data_error('RUN-DEVICE-DATA-008','Real rank-4 leaf is absent after copyin.')
    call account_leaf(size(value), storage_size(0.0_wp), leaf_count, payload_bytes)
  end subroutine
  subroutine map_integer_1(value, leaf_count, payload_bytes)
    integer, allocatable, intent(inout) :: value(:)
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    if (.not.allocated(value)) return
    if (size(value) == 0) return
    call acc_copyin(value, int(size(value),8)*int(storage_size(0)/8,8))
    if (.not.acc_is_present(value, int(size(value),8)*int(storage_size(0)/8,8))) call device_data_error('RUN-DEVICE-DATA-008','Integer leaf is absent after copyin.')
    call account_leaf(size(value), storage_size(0), leaf_count, payload_bytes)
  end subroutine
  subroutine map_character_1(value, leaf_count, payload_bytes)
    character(len=64), allocatable, intent(inout) :: value(:)
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    if (.not.allocated(value)) return
    if (size(value) == 0) return
    call acc_copyin(value, int(size(value),8)*int(storage_size(value)/8,8))
    if (.not.acc_is_present(value, int(size(value),8)*int(storage_size(value)/8,8))) call device_data_error('RUN-DEVICE-DATA-008','Character leaf is absent after copyin.')
    call account_leaf(size(value), storage_size(value), leaf_count, payload_bytes)
  end subroutine
  subroutine check_real_1(value, leaf_count, payload_bytes)
    real(kind=wp), allocatable, intent(inout) :: value(:)
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    if (.not.allocated(value)) return
    if (size(value) == 0) return
    if (.not.acc_is_present(value, int(size(value),8)*int(storage_size(0.0_wp)/8,8))) call device_data_error('RUN-DEVICE-DATA-009','Mapped leaf is unexpectedly absent.')
    call account_leaf(size(value), storage_size(0.0_wp), leaf_count, payload_bytes)
  end subroutine

  subroutine check_real_2(value, leaf_count, payload_bytes)
    real(kind=wp), allocatable, intent(inout) :: value(:,:)
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    if (.not.allocated(value)) return
    if (size(value) == 0) return
    if (.not.acc_is_present(value, int(size(value),8)*int(storage_size(0.0_wp)/8,8))) call device_data_error('RUN-DEVICE-DATA-009','Mapped leaf is unexpectedly absent.')
    call account_leaf(size(value), storage_size(0.0_wp), leaf_count, payload_bytes)
  end subroutine

  subroutine check_real_3(value, leaf_count, payload_bytes)
    real(kind=wp), allocatable, intent(inout) :: value(:,:,:)
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    if (.not.allocated(value)) return
    if (size(value) == 0) return
    if (.not.acc_is_present(value, int(size(value),8)*int(storage_size(0.0_wp)/8,8))) call device_data_error('RUN-DEVICE-DATA-009','Mapped leaf is unexpectedly absent.')
    call account_leaf(size(value), storage_size(0.0_wp), leaf_count, payload_bytes)
  end subroutine

  subroutine check_real_4(value, leaf_count, payload_bytes)
    real(kind=wp), allocatable, intent(inout) :: value(:,:,:,:)
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    if (.not.allocated(value)) return
    if (size(value) == 0) return
    if (.not.acc_is_present(value, int(size(value),8)*int(storage_size(0.0_wp)/8,8))) call device_data_error('RUN-DEVICE-DATA-009','Mapped leaf is unexpectedly absent.')
    call account_leaf(size(value), storage_size(0.0_wp), leaf_count, payload_bytes)
  end subroutine

  subroutine check_integer_1(value, leaf_count, payload_bytes)
    integer, allocatable, intent(inout) :: value(:)
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    if (.not.allocated(value)) return
    if (size(value) == 0) return
    if (.not.acc_is_present(value, int(size(value),8)*int(storage_size(0)/8,8))) call device_data_error('RUN-DEVICE-DATA-009','Mapped leaf is unexpectedly absent.')
    call account_leaf(size(value), storage_size(0), leaf_count, payload_bytes)
  end subroutine

  subroutine check_character_1(value, leaf_count, payload_bytes)
    character(len=64), allocatable, intent(inout) :: value(:)
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    if (.not.allocated(value)) return
    if (size(value) == 0) return
    if (.not.acc_is_present(value, int(size(value),8)*int(storage_size(value)/8,8))) call device_data_error('RUN-DEVICE-DATA-009','Mapped leaf is unexpectedly absent.')
    call account_leaf(size(value), storage_size(value), leaf_count, payload_bytes)
  end subroutine

  subroutine unmap_real_1(value, leaf_count, payload_bytes)
    real(kind=wp), allocatable, intent(inout) :: value(:)
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    if (.not.allocated(value)) return
    if (size(value) == 0) return
    if (.not.acc_is_present(value, int(size(value),8)*int(storage_size(0.0_wp)/8,8))) call device_data_error('RUN-DEVICE-DATA-009','Mapped leaf is unexpectedly absent.')
    call acc_delete_finalize(value, int(size(value),8)*int(storage_size(0.0_wp)/8,8))
    if (acc_is_present(value, int(size(value),8)*int(storage_size(0.0_wp)/8,8))) call device_data_error('RUN-DEVICE-DATA-010','Leaf remains present after delete.')
    call account_leaf(size(value), storage_size(0.0_wp), leaf_count, payload_bytes)
  end subroutine

  subroutine unmap_real_2(value, leaf_count, payload_bytes)
    real(kind=wp), allocatable, intent(inout) :: value(:,:)
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    if (.not.allocated(value)) return
    if (size(value) == 0) return
    if (.not.acc_is_present(value, int(size(value),8)*int(storage_size(0.0_wp)/8,8))) call device_data_error('RUN-DEVICE-DATA-009','Mapped leaf is unexpectedly absent.')
    call acc_delete_finalize(value, int(size(value),8)*int(storage_size(0.0_wp)/8,8))
    if (acc_is_present(value, int(size(value),8)*int(storage_size(0.0_wp)/8,8))) call device_data_error('RUN-DEVICE-DATA-010','Leaf remains present after delete.')
    call account_leaf(size(value), storage_size(0.0_wp), leaf_count, payload_bytes)
  end subroutine

  subroutine unmap_real_3(value, leaf_count, payload_bytes)
    real(kind=wp), allocatable, intent(inout) :: value(:,:,:)
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    if (.not.allocated(value)) return
    if (size(value) == 0) return
    if (.not.acc_is_present(value, int(size(value),8)*int(storage_size(0.0_wp)/8,8))) call device_data_error('RUN-DEVICE-DATA-009','Mapped leaf is unexpectedly absent.')
    call acc_delete_finalize(value, int(size(value),8)*int(storage_size(0.0_wp)/8,8))
    if (acc_is_present(value, int(size(value),8)*int(storage_size(0.0_wp)/8,8))) call device_data_error('RUN-DEVICE-DATA-010','Leaf remains present after delete.')
    call account_leaf(size(value), storage_size(0.0_wp), leaf_count, payload_bytes)
  end subroutine

  subroutine unmap_real_4(value, leaf_count, payload_bytes)
    real(kind=wp), allocatable, intent(inout) :: value(:,:,:,:)
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    if (.not.allocated(value)) return
    if (size(value) == 0) return
    if (.not.acc_is_present(value, int(size(value),8)*int(storage_size(0.0_wp)/8,8))) call device_data_error('RUN-DEVICE-DATA-009','Mapped leaf is unexpectedly absent.')
    call acc_delete_finalize(value, int(size(value),8)*int(storage_size(0.0_wp)/8,8))
    if (acc_is_present(value, int(size(value),8)*int(storage_size(0.0_wp)/8,8))) call device_data_error('RUN-DEVICE-DATA-010','Leaf remains present after delete.')
    call account_leaf(size(value), storage_size(0.0_wp), leaf_count, payload_bytes)
  end subroutine

  subroutine unmap_integer_1(value, leaf_count, payload_bytes)
    integer, allocatable, intent(inout) :: value(:)
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    if (.not.allocated(value)) return
    if (size(value) == 0) return
    if (.not.acc_is_present(value, int(size(value),8)*int(storage_size(0)/8,8))) call device_data_error('RUN-DEVICE-DATA-009','Mapped leaf is unexpectedly absent.')
    call acc_delete_finalize(value, int(size(value),8)*int(storage_size(0)/8,8))
    if (acc_is_present(value, int(size(value),8)*int(storage_size(0)/8,8))) call device_data_error('RUN-DEVICE-DATA-010','Leaf remains present after delete.')
    call account_leaf(size(value), storage_size(0), leaf_count, payload_bytes)
  end subroutine

  subroutine unmap_character_1(value, leaf_count, payload_bytes)
    character(len=64), allocatable, intent(inout) :: value(:)
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    if (.not.allocated(value)) return
    if (size(value) == 0) return
    if (.not.acc_is_present(value, int(size(value),8)*int(storage_size(value)/8,8))) call device_data_error('RUN-DEVICE-DATA-009','Mapped leaf is unexpectedly absent.')
    call acc_delete_finalize(value, int(size(value),8)*int(storage_size(value)/8,8))
    if (acc_is_present(value, int(size(value),8)*int(storage_size(value)/8,8))) call device_data_error('RUN-DEVICE-DATA-010','Leaf remains present after delete.')
    call account_leaf(size(value), storage_size(value), leaf_count, payload_bytes)
  end subroutine

  subroutine update_host_real_1(value, leaf_count, payload_bytes)
    real(kind=wp), allocatable, intent(inout) :: value(:)
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    if (.not.allocated(value)) return
    if (size(value) == 0) return
    if (.not.acc_is_present(value, int(size(value),8)*int(storage_size(0.0_wp)/8,8))) call device_data_error('RUN-DEVICE-DATA-009','Mapped leaf is unexpectedly absent.')
    call acc_update_self(value, int(size(value),8)*int(storage_size(0.0_wp)/8,8))
    call account_leaf(size(value), storage_size(0.0_wp), leaf_count, payload_bytes)
  end subroutine

  subroutine update_host_real_2(value, leaf_count, payload_bytes)
    real(kind=wp), allocatable, intent(inout) :: value(:,:)
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    if (.not.allocated(value)) return
    if (size(value) == 0) return
    if (.not.acc_is_present(value, int(size(value),8)*int(storage_size(0.0_wp)/8,8))) call device_data_error('RUN-DEVICE-DATA-009','Mapped leaf is unexpectedly absent.')
    call acc_update_self(value, int(size(value),8)*int(storage_size(0.0_wp)/8,8))
    call account_leaf(size(value), storage_size(0.0_wp), leaf_count, payload_bytes)
  end subroutine

  subroutine update_host_real_3(value, leaf_count, payload_bytes)
    real(kind=wp), allocatable, intent(inout) :: value(:,:,:)
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    if (.not.allocated(value)) return
    if (size(value) == 0) return
    if (.not.acc_is_present(value, int(size(value),8)*int(storage_size(0.0_wp)/8,8))) call device_data_error('RUN-DEVICE-DATA-009','Mapped leaf is unexpectedly absent.')
    call acc_update_self(value, int(size(value),8)*int(storage_size(0.0_wp)/8,8))
    call account_leaf(size(value), storage_size(0.0_wp), leaf_count, payload_bytes)
  end subroutine

  subroutine update_host_real_4(value, leaf_count, payload_bytes)
    real(kind=wp), allocatable, intent(inout) :: value(:,:,:,:)
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    if (.not.allocated(value)) return
    if (size(value) == 0) return
    if (.not.acc_is_present(value, int(size(value),8)*int(storage_size(0.0_wp)/8,8))) call device_data_error('RUN-DEVICE-DATA-009','Mapped leaf is unexpectedly absent.')
    call acc_update_self(value, int(size(value),8)*int(storage_size(0.0_wp)/8,8))
    call account_leaf(size(value), storage_size(0.0_wp), leaf_count, payload_bytes)
  end subroutine

  subroutine update_host_integer_1(value, leaf_count, payload_bytes)
    integer, allocatable, intent(inout) :: value(:)
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    if (.not.allocated(value)) return
    if (size(value) == 0) return
    if (.not.acc_is_present(value, int(size(value),8)*int(storage_size(0)/8,8))) call device_data_error('RUN-DEVICE-DATA-009','Mapped leaf is unexpectedly absent.')
    call acc_update_self(value, int(size(value),8)*int(storage_size(0)/8,8))
    call account_leaf(size(value), storage_size(0), leaf_count, payload_bytes)
  end subroutine

  subroutine update_host_character_1(value, leaf_count, payload_bytes)
    character(len=64), allocatable, intent(inout) :: value(:)
    integer, intent(inout) :: leaf_count
    integer(int64), intent(inout) :: payload_bytes
    if (.not.allocated(value)) return
    if (size(value) == 0) return
    if (.not.acc_is_present(value, int(size(value),8)*int(storage_size(value)/8,8))) call device_data_error('RUN-DEVICE-DATA-009','Mapped leaf is unexpectedly absent.')
    call acc_update_self(value, int(size(value),8)*int(storage_size(value)/8,8))
    call account_leaf(size(value), storage_size(value), leaf_count, payload_bytes)
  end subroutine

end module device_data
